# Generated by Django 4.1.4 on 2022-12-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_alter_pizza_pizza_name_alter_topping_topping_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image_url',
            field=models.URLField(default='https://www.pngitem.com/pimgs/m/504-5040768_meat-lovers-pizza-hd-png-download.png'),
        ),
    ]
